export const products = [
  {
    id: "p1",
    name: "Chunky Knit Throw Blanket",
    price: 34.99,
    originalPrice: 49.99,
    image: "https://placehold.co/400x400/6C63FF/ffffff?text=Throw+Blanket",
    category: "home",
    tags: ["cozy", "living room", "gift", "neutral"],
    description: "Oversized cream knit throw, perfect for a reading nook.",
  },
  {
    id: "p2",
    name: "Wireless Earbuds Pro",
    price: 39.99,
    originalPrice: 59.99,
    image: "https://placehold.co/400x400/6C63FF/ffffff?text=Earbuds",
    category: "electronics",
    tags: ["tech", "audio", "gift", "budget"],
    description: "Noise-isolating earbuds with 24hr battery case.",
  },
  {
    id: "p3",
    name: "Minimalist Desk Lamp",
    price: 22.5,
    image: "https://placehold.co/400x400/6C63FF/ffffff?text=Desk+Lamp",
    category: "home",
    tags: ["desk setup", "office", "budget", "neutral"],
    description: "Adjustable warm-light LED lamp with a matte black finish.",
  },
  {
    id: "p4",
    name: "Ceramic Pour-Over Coffee Set",
    price: 28.0,
    originalPrice: 36.0,
    image: "https://placehold.co/400x400/6C63FF/ffffff?text=Coffee+Set",
    category: "kitchen",
    tags: ["coffee", "gift", "cozy"],
    description: "Hand-glazed ceramic dripper and matching mug.",
  },
  {
    id: "p5",
    name: "Weighted Sherpa Hoodie",
    price: 45.0,
    image: "https://placehold.co/400x400/6C63FF/ffffff?text=Hoodie",
    category: "apparel",
    tags: ["cozy", "winter", "gift"],
    description: "Fleece-lined hoodie for cold mornings.",
  },
  {
    id: "p6",
    name: "Portable Bluetooth Speaker",
    price: 27.99,
    originalPrice: 34.99,
    image: "https://placehold.co/400x400/6C63FF/ffffff?text=Speaker",
    category: "electronics",
    tags: ["tech", "audio", "budget", "outdoor"],
    description: "Waterproof speaker, 12hr playtime, clips to a bag.",
  },
  {
    id: "p7",
    name: "Linen Throw Pillow Cover Set",
    price: 19.99,
    image: "https://placehold.co/400x400/6C63FF/ffffff?text=Pillow+Set",
    category: "home",
    tags: ["cozy", "living room", "neutral", "budget"],
    description: "Set of 2 natural linen covers, fits 18x18 inserts.",
  },
  {
    id: "p8",
    name: "Stainless Steel Pour Kettle",
    price: 31.5,
    image: "https://placehold.co/400x400/6C63FF/ffffff?text=Kettle",
    category: "kitchen",
    tags: ["coffee", "gift"],
    description: "Gooseneck kettle for controlled pour-over brewing.",
  },
];